# Generated by Django 4.0.5 on 2022-07-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, choices=[('sales', 'sales'), ('support', 'support'), ('management', 'management')], max_length=25),
        ),
    ]
